name: build

on: [push, pull_request]

jobs:
  windows:
    name: Test on ${{ matrix.os }} with arch ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [Win32, x64]
        os: [windows-2019]
        include:
        - arch: x64
          os: ubuntu-latest
          experimental: true
    steps:
    - uses: actions/checkout@v1
    
    - name: cmake configure windows
      if: matrix.os == 'windows-2019'
      run: cmake . -A ${{matrix.arch}}
        
    - name: cmake configure ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: cmake .
      
    - name: cmake build windows
      if: matrix.os == 'windows-2019'
      run: cmake --build . -- -property:Configuration=Release

    - name: cmake build ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: cmake --build .


    - uses: actions/upload-artifact@v1
      if: matrix.os == 'windows-2019'
      with:
        name: hedra-core-${{matrix.arch}}-${{ matrix.os }}
        path: Release/hedracore.dll

    - uses: actions/upload-artifact@v1
      if: matrix.os == 'ubuntu-latest'
      with:
        name: hedra-core-${{matrix.arch}}-${{ matrix.os }}
        path: libhedracore.so