name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake configure
      run: cmake . -A x64
    - name: cmake build
      run: cmake --build . -- -property:Configuration=Release -verbosity:minimal
    - name: dir
      shell: bash
      run: ls
